### ISSUE TITLE
IApplicationShutdown

### ISSUE THREAD

**Issue by Ph47** [aspnet/PlatformAbstractions#1]
I am writing here because of https://github.com/aspnet/Announcements/blob/master/CONTRIBUTING.md. 

As stated here (https://github.com/aspnet/Announcements/issues/104) IApplicationShutdown must be located in Microsoft.Extensions.PlatformAbstractions.
 
I have following dependency: "Microsoft.Extensions.PlatformAbstractions": "1.0.0-rc2-*" ("*" is 16258 now). It really contains some interfaces but does not contains IApplicationShutdown.

What is right way to catch app shutdown in asp vnext?

**Comment by MaximRouiller** [comment]
https://github.com/aspnet/dnx/pull/2979

https://github.com/aspnet/Hosting/blob/1.0.0-rc1/src/Microsoft.AspNet.Hosting.Abstractions/IApplicationLifetime.cs

**Comment by davidfowl** [comment]
Yep @MaximRouiller
