### ISSUE TITLE
Only infer 64-bit RID on non-Windows

### ISSUE THREAD

**Issue by anurse** [aspnet/PlatformAbstractions#16]
Because there are no CoreCLR packages for x86 on those platforms and Mono doesn't need RIDs. This causes problems with NuGet's guardrails.

See NuGet/Home#1941

**Comment by muratg** [comment]
Perhaps for Windows too?  

cc @pakrym

**Comment by muratg** [comment]
Needed still?  @pakrym @anurse

**Comment by muratg** [comment]
@anurse looks like NuGet issue was closed. Any work on our side still required?

**Comment by anurse** [comment]
In theory yes, since we still have the extension method.

**Comment by muratg** [comment]
@pakrym Are you able to take this?

**Comment by pakrym** [comment]
Yep

**Comment by muratg** [comment]
@pakrym Did you sync-up with @anurse on this? Still in RTM?

**Comment by pakrym** [comment]
@anurse said we don't need this anymore, closing.
