### ISSUE TITLE
Consider renaming IApplicationEnvironment.ApplicationBasePath to ApplicationContentBasePath

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/PlatformAbstractions#26]
The name `IApplicationEnvironment.ApplicationBasePath` may be confusing as it doesn't necessarily reflect the base path from the runtime's (CLR's) point of view, i.e. where the application assembly was located. Rather, it's an ASP.NET Core specific primitive that's set by the `WebHostBuilder` and more accurately represents where code should look to find content files for the application. Content files could include application configuration files, views, web content folders, etc. `IHostingEnvironment.WebRootPath` would still default to a sub-folder under this path of course.

We should consider changing the name of the property to `ApplicationContentBasePath` to make it better match the semantic meaning of the value.

@lodejard @anurse

**Comment by CoskunSunali** [comment]
That is a good suggestion.

You could even go for `IApplicationEnvironment.ContentPath` since the interface name already contains the word `Application` and it is obvious that the property belongs to the `Application` and not something else.

**Comment by davidfowl** [comment]
Ugh, I don't like it, it's weird. Maybe we should nuke this interface and move something into `IHostingEnvironment` since it's become web specific.

**Comment by lodejard** [comment]
I was actually wondering why the properties didn't get moved when the source of the information changed. But it shouldn't be called application base, that's super confusing at this point.

**Comment by davidfowl** [comment]
I'm going to have to disagree there. I think we should move things to IHostingEnvironment and abandon this interface. On IHostingEnvironment we can change it to whatever we want. This abstraction represents the BCL application base and I 100% agree that in this new world, it's confusing to have it be different from that.

**Comment by CoskunSunali** [comment]
Sounds even better @davidfowl.

**Comment by davidfowl** [comment]
Closing this as I opened another issue on hosting

**Comment by lodejard** [comment]
"I'm going to have to disagree there. I think we should move things to IHostingEnvironment and abandon this interface."

You disagreed, then said exactly what I said. The properties should have been moved to IHostingEnvironment originally.

**Comment by davidfowl** [comment]
Sorta.
