### ISSUE TITLE
Remove private reflection for Assembly.Location in netstandard1.3

### ISSUE THREAD

**Issue by pranavkm** [aspnet/PlatformAbstractions#29]
Assembly.Location is only available in netstandard1.5 which would require us to retarget PlatformAbstractions. We could consider removing the API (doesn't seem like anybody uses it) or target netstandard1.5

**Comment by Eilon** [comment]
@pranavkm @davidfowl any idea what the resolution to this will look like?

**Comment by pranavkm** [comment]
We can remove the property. I don't think it's used anywhere in particular and it doesn't seem super useful.

**Comment by pranavkm** [comment]
The property in question:

**Comment by davidfowl** [comment]
Yes we should just remove the property.

**Comment by Eilon** [comment]
Okie dokie.

**Comment by muratg** [comment]
PR is open still.  Is this good to merge and close?

**Comment by pranavkm** [comment]
Yup I'll merge it in. Didn't want to add breaking changes to the mix
