### ISSUE TITLE
Switch to using System.Runtime.InteropServices.RuntimeInformation where appropriate

### ISSUE THREAD

**Issue by anurse** [aspnet/PlatformAbstractions#34]
(this can be done in RTM)

/cc @muratg

**Comment by Eilon** [comment]
@BrennanConroy can you figure out what we need to do here?

**Comment by davidfowl** [comment]
We can't do anything until we get new BCL packages.

**Comment by Eilon** [comment]
Ok, hopefully today.

**Comment by muratg** [comment]
This should be doable now.

**Comment by muratg** [comment]
@BrennanConroy unblocked?

**Comment by BrennanConroy** [comment]
Nope, we need to get the RC3 System.* packages

**Comment by natemcmaster** [comment]
This is the cause of https://github.com/aspnet/EntityFramework/issues/5483

**Comment by BrennanConroy** [comment]
OSVersion isn't supported yet https://github.com/dotnet/corefx/issues/4741
RuntimeType does not exist in RuntimeInformation, we use if to test for CLR, CoreCLR, or Mono

**Comment by pranavkm** [comment]
@BrennanConroy where do we use those two properties?

**Comment by BrennanConroy** [comment]
Testing, EntityFramework, MusicStore, Performance, Hosting

**Comment by BrennanConroy** [comment]
Should I leave the spots that use OsVersion and RuntimeType and remove the references to the other types on the RuntimeEnvironment type?

**Comment by JunTaoLuo** [comment]
:shipit:

**Comment by BrennanConroy** [comment]
Done, will make an issue in Common for removing the RuntimeEnvironment.Sources package once RuntimeInformation has more features.
