### ISSUE TITLE
Consider removing IApplicationEnvironment \ IRuntimeEnvironment

### ISSUE THREAD

**Issue by pranavkm** [aspnet/PlatformAbstractions#36]
* Runtime components in Asp.Net have switched to using `IHostingEnvironment` over `IApplicationEnvironment`. 
* CoreFX has a `RuntimeInformation` type that has most of the API that `IRuntimeEnvironment` supports.

Given these, we could remove these types from our codebase. We can follow up with a change to the CLI so that it removes one arc of the cyclic dependency that is currently present between the two.

cc @davidfowl  \ @Eilon

**Comment by pranavkm** [comment]
Related to https://github.com/aspnet/PlatformAbstractions/issues/34

**Comment by natemcmaster** [comment]
Is this also going into RC2?

**Comment by anurse** [comment]
Is the goal here to remove the interfaces, or the implementations as well? We are definitely using the implementations in a number of places (and `RuntimeInformation` is not sufficient to cover those)

**Comment by pranavkm** [comment]
@anurse  - the implementations will stay. Here's the PR for it https://github.com/aspnet/PlatformAbstractions/pull/39

**Comment by anurse** [comment]
Yeah, I saw the PR and it looked OK. I was just concerned there was going to be a part 2 that removed the implementations :P

**Comment by pranavkm** [comment]
The hope was to move the RID inference code into Cli and switch to using `RuntimeInformation` in our code. Part of a set of changes to unbreak cycles between CLI and our repos.

**Comment by Eilon** [comment]
@pranavkm any further work for this?

**Comment by pranavkm** [comment]
Needs to be checked in. Waiting for the new CLI to do this.

**Comment by Eilon** [comment]
Ah ok!

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/PlatformAbstractions/commit/95d352a1886ea53bab837714e0a47272657087a5

**Comment by Eilon** [comment]
Done/Closed/Open?

**Comment by DavidArno** [comment]
Can anyone explain the logic behind removing these interfaces? This has just made testing harder for no logical reason that I can see.

**Comment by pranavkm** [comment]
@DavidArno - we no longer use these interfaces in our codebases. In the past, DNX owned creating \ populating \ injecting these interfaces. However since the move to CLI, these are primarily wrappers for `System.Runtime.InteropServices.RuntimeInformation` and `AppContext.BaseDirectory` \ `AppDomain.BaseDirectory`. We didn't find it necessary to continue maintaining abstractions for wrappers. 

We do have an `IHostingEnvironment` interface which has abstractions for web related things such as content root and web root which is what all our middlewares use.
