### ISSUE TITLE
Discussion: Remove IApplicationEnvironment \ IHostingEnvironment

### ISSUE THREAD

**Issue by pranavkm** [aspnet/PlatformAbstractions#37]
Discussion for https://github.com/aspnet/Announcements/issues/171

As a follow up to https://github.com/aspnet/Announcements/issues/157, we're removing `IApplicationEnvironment` and `IRuntimeEnvironment` interfaces. Startup code that uses `IApplicationEnvironment` should be modified to use `IHostingEnvironment`:

Before:

```
public Startup(IApplicationEnvironment applicationEnvironment)
{
   var builder = new ConfigurationBuilder()
        .SetBasePath(applicationEnvironment.ApplicationBasePath)
    ...
```

After

```
public Startup(IHostingEnvironment hostingEnvironment)
{
   var builder = new ConfigurationBuilder()
        .SetBasePath(hostingEnvironment.ContentRootPath)
    ...
```

The concrete types backing `IApplicationEnvironment` and `IRuntimeEnvironment` will continue to be accessible statically via `Microsoft.Extensions.PlatformAbstractions.PlatformServices.Default`.
Use https://github.com/aspnet/PlatformAbstractions/issues/37 for further discussion.

**Comment by michaelherndon** [comment]
ContentRootPath feels like it implies that it is wwwroot. Is that correct or is it the Application Root?  

inquiring minds want to know.

**Comment by pranavkm** [comment]
`ContentRootPath` points to the application root (content here means things like Views). `IHostingEnvironment` has a [`WebRootPath`](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting.Abstractions/IHostingEnvironment.cs#L28) which points to `wwwroot`.

**Comment by yzorg** [comment]
Did you consider "WebApplicationPath" instead of "ContentRootPath".  To me the web application includes what VS calls "content files" (configuration files, project.json), the dotnet binaries in ./bin, and the static web files in ./wwwroot.  

I get that with the unification of ASP.NET into the dotnet CLI that ApplicationBasePath now needs to point to the ./bin directory, but why not use "Web" prefix to mean the directory above that?  

Is the team intentionally staying away from the word "Web" in property names?

**Comment by ciel** [comment]
So with this change, where does that move things like `UseMvc` and `UseCors` and `UseStaticFiles` over to?

**Comment by pranavkm** [comment]
@yzorg, feel free to file a bug for this in https://github.com/aspnet/Hosting which is where `IHostingEnvironment` is defined.They had some difficulty coming up with the current name so they might be open to a change here.

@ciel, you're looking for `IApplicationBuilder` which remains unchanged.

**Comment by ciel** [comment]
Yeah, @pranavkm - I was getting mixed up. The change is in the constructor. I was replacing it on the actual `Configure` method, which broke everything in there. I'm good now, thanks. Sorry for being stupid.

**Comment by yzorg** [comment]
Thank you @pranavkm, just cross posted my question there!

**Comment by Tragetaschen** [comment]
Is `PlatformServices.Default.Application.ApplicationVersion` the correct replacement for `IApplicationEnvironment.ApplicationVersion`?

**Comment by Tragetaschen** [comment]
(talking to myself) No, it's probably
```cs
(Attribute.GetCustomAttribute(Assembly.GetEntryAssembly(),typeof(AssemblyInformationalVersionAttribute)) as AssemblyInformationalVersionAttribute).InformationalVersion;
```

**Comment by ShadowDancer** [comment]
Where are things like RuntimeVersion, Hosting.OperatingSystem, Hosting.OperatingSystemVersion, ApplicationVersion located now?

**Comment by davidfowl** [comment]
This library existed as an interim solution until there was a BCL API to get similar information. It will likely go away in favor of https://github.com/aspnet/PlatformAbstractions/issues/34

**Comment by pranavkm** [comment]
@ShadowDancer - you need https://www.nuget.org/packages/System.Runtime.InteropServices.RuntimeInformation/4.0.0-rc2-24027. However there are issues with this package in the rc2 release which make it difficult to use with a net4x application. The RC3 version of this package should address these issues. In the interim you can continue using these the properties you're looking for via `PlatformServices.Default.RuntimeEnvironment`

**Comment by hishamco** [comment]
@pranavkm I think this should be closed, while `IApplicationEnvironment` is already remove

**Comment by pranavkm** [comment]
Thanks @hishamco 👍
