### ISSUE TITLE
Method Not Found 'Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment Microsoft.Extensions.PlatformAbstractions.PlatformServices.get_Application()

### ISSUE THREAD

**Issue by shima20** [aspnet/PlatformAbstractions#40]
I'm receiving the following error in my Startup.cs when using rc2 from aspnetcirelease.  This seemed to happen all of a sudden after it was working fine.

![image](https://cloud.githubusercontent.com/assets/9735056/15154347/e2100f28-1691-11e6-830a-1fd4d1d4e40c.png)

**Comment by davidfowl** [comment]
That can happen when you use floating versions. Things change from restore to restore. What does your `project.json` and application look like? And what versions of stuff is it using?

**Comment by shima20** [comment]
@davidfowl  Here is my project.json

{
    "version": "1.0.0-*",
    "description": "Portal",
    "webroot": "wwwroot",
    "commands": {
        "web": "Portal",
        "ef": "EntityFrameworkCore.Commands"
    },
    "compilationOptions": {
        "emitEntryPoint": true
    },
    "dependencies": {

        "Portal.Models": "1.0.0-*",
        "Portal.Data": "1.0.0-*",
        "Portal.Services": "1.0.0-*",
        "Microsoft.AspNetCore.Hosting": "1.0.0-rc2-*",
        "Microsoft.AspNetCore.IISPlatformHandler": "1.0.0-rc2-*",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-*",
        "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-*",
        "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-rc2-*",
        "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-rc2-*",
        "Microsoft.Framework.DependencyInjection.Abstractions": "1.0.0-beta8",
        "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-*",
        "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-*",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-20766",
        "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-*",
        "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-*",
        "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0-rc2-*",
        "OpenIddict.Core": "1.0.0-*",
        "OpenIddict.EF": "1.0.0-*"
    },
    "frameworks": {
        "net451": {
            "frameworkAssemblies": {
                "System.Runtime": {
                    "type": "build",
                    "version": "4.0.10.0"
                }
            }
        },

        "netstandardapp1.5": {
            "dependencies": {
                "NETStandard.Library": "1.5.0-*"
            },

            "imports": [
                "dnxcore50",
                "portable-net451+win8"
            ]
        }
    },

    "exclude": [
        "wwwroot",
        "node_modules"
    ],
    "publishExclude": [
        "**.user",
        "**.vspscc"
    ]
}

**Comment by davidfowl** [comment]
I'd suggesting starting over from https://github.com/aspnet/cli-samples as a baseline. The dependencies and target frameworks don't reflect the latest set of changes.

**Comment by shima20** [comment]
Which project.json file would you recommend to follow?

**Comment by shima20** [comment]
I thought the AspnetCiRelease feed was more of a close to stable version compared to dev

**Comment by moozzyk** [comment]
First of all don't mix versions - you are using a beta8 package with rc2:
```
Microsoft.Framework.DependencyInjection.Abstractions": "1.0.0-beta8"
```
and you are using floating rc2 versions (`*`) and specific ones (`"1.0.0-rc2-20766"`). 

At the moment aspnetcirelease and aspnetcidev are functionally close. However aspentcidev already moved to  post RC2 packages so if you are on aspnetcidev you may end up using older rc2 packages than rc2 packages from the release feed (because the counterparts of the latest from release feeds are already rc3 in the dev feeds and you specified `-rc2-` versions in project.json). And actually you might be better off using the aspnetrelease than aspnetcirelease (because aspnetci{branch} feeds contain packages that are not tested).

**Comment by shima20** [comment]
Thanks @moozzyk.  Do you have any clear instructions on how to install from the "aspnetrelease" and what the final project.json file should look like?  I think I've been struggling with what to put in the json file.

**Comment by moozzyk** [comment]
Feeds are specified in NuGet.config file not project.json (or you can provide -s option to restore). You also need the regular NuGet feed. You can find a link to aspnetrelease feed here: https://myget.org/gallery/aspnetrelease. You want to use v3 feed.

**Comment by shima20** [comment]
@moozzyk - Here is my Nuget.config placed where the global.json is.  Do I just do "dotnet restore" after that?

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="AspNetCiRelease" value="https://www.myget.org/F/aspnetrelease/api/v3/index.json" />
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>

**Comment by moozzyk** [comment]
yes (after you fixed versions in your project.json - note `Microsoft.Framework.DependencyInjection.Abstraction` was renamed to `Microsoft.Extensions.DependencyInjection.Abstractions`)

**Comment by shima20** [comment]
@moozzyk - Is this still valid in the project.json?

`"frameworks": {
        "net451": {
            "frameworkAssemblies": {
                "System.Runtime": {
                    "type": "build",
                    "version": "4.0.10.0"
                }
            }
        },

        "netstandardapp1.5": {
            "dependencies": {
                "NETStandard.Library": "1.5.0-*"
            },

            "imports": [
                "dnxcore50",
                "portable-net451+win8"
            ]
        }
    },`

**Comment by shima20** [comment]
@moozzyk - I followed the steps however, I'm still getting the same error in startup.cs

**Comment by moozzyk** [comment]
share you application

**Comment by shima20** [comment]
Is there something in particular I should share? The solution has several different projects.

Portal
Portal.Data
Portal.Models
Portal.Services

**Comment by moozzyk** [comment]
Ideally provide a minimal but complete repro so that I can run it and see what's wrong.

**Comment by shima20** [comment]
Startup.cs

```
public static void Main(string[] args)
        {
            var application = new WebHostBuilder()
                //.UseCaptureStartupErrors(captureStartupError: true)
                .ConfigureLogging(options => options.AddDebug(minLevel: LogLevel.Debug))
                .ConfigureLogging(options => options.AddConsole(minLevel: LogLevel.Debug))
                .UseIISPlatformHandlerUrl()
                .UseKestrel()
                .UseStartup<Startup>()
                .Build();

            application.Run();

        }
```

**Comment by moozzyk** [comment]
I am pretty sure the complete application is more that that. Just create a repo on github which I can clone compile and run. I can't run what you provided without adding a bunch on my code in which case what you see won't repro. Alternatively, clone https://github.com/aspnet/cli-samples and start modifying the HelloMvc app until you get what you need. HelloMvc app works.

**Comment by shima20** [comment]
Thanks @moozzyk - Let me try that and see what happens

**Comment by shima20** [comment]
@moozzyk - I was able to download the cli-samples solution, however I keep getting Package Restore failed 'unknown keyword platform'

**Comment by shima20** [comment]
Here is the dotnet info:

Product Information:
 Version:     1.0.0-preview1-002700
 Commit Sha:  0336f6bb34

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

**Comment by moozzyk** [comment]
This was fixed ages ago - I don't know how it is possible with 1.0.0-preview1-002700. I am actually the same version you are using and don't see any problem. Are you sure you do `dotnet restore` and not `dnu restore`?

**Comment by shima20** [comment]
Yes, I ran dotnet restore.  Curious, is there a way to run debug through IIS Express (navigation bar in VS) instead of doing dotnet run?

**Comment by shima20** [comment]
Not sure if this helps any....

```
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git
C:\Users\myusername\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-20221\bin\dnx.exe "C:\Users\myusername\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-20221\bin\lib\Microsoft.Dnx.Tooling\Microsoft.Dnx.Tooling.dll" restore "C:\Users\myusername\Documents\GitHub\cli-samples\HelloMvc" -f "C:\Program Files (x86)\Microsoft Web Tools\DNU"
Microsoft .NET Development Utility Clr-x86-1.0.0-rc2-20221
  CACHE https://www.nuget.org/api/v2/
  CACHE https://www.myget.org/F/aspnetrelease/api/v3/index.json
  CACHE https://api.nuget.org/v3/index.json
Restoring packages for C:\Users\myusername\Documents\GitHub\cli-samples\HelloMvc\project.json
----------
C:\Users\myusername\Documents\GitHub\cli-samples\HelloMvc\project.json(0,0): Error: Microsoft.Dnx.Runtime.FileFormatException: unknown keyword platform ---> System.InvalidOperationException: unknown keyword platform
   at Microsoft.Dnx.Runtime.LibraryDependencyType.Parse(String keyword)
   at Microsoft.Dnx.Runtime.ProjectReader.PopulateDependencies(String projectPath, IList`1 results, JsonObject settings, String propertyName, Boolean isGacOrFrameworkReference)
   at Microsoft.Dnx.Runtime.ProjectReader.ReadProject(Stream stream, String projectName, String projectPath, ICollection`1 diagnostics)
   at Microsoft.Dnx.Runtime.Project.TryGetProject(String path, Project& project, ICollection`1 diagnostics)
   --- End of inner exception stack trace ---
   at Microsoft.Dnx.Runtime.Project.TryGetProject(String path, Project& project, ICollection`1 diagnostics)
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
unknown keyword platform
NuGet Config files used:
    C:\Users\myusername\AppData\Roaming\NuGet\nuget.config
    C:\Users\myusername\Documents\GitHub\cli-samples\nuget.config
Feeds used:
    https://www.nuget.org/api/v2/
    https://www.myget.org/F/aspnetrelease/api/v3/flatcontainer/
    https://api.nuget.org/v3-flatcontainer/
    C:\Program Files (x86)\Microsoft Web Tools\DNU
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git
C:\Users\myusername\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-20221\bin\dnx.exe "C:\Users\myusername\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-20221\bin\lib\Microsoft.Dnx.Tooling\Microsoft.Dnx.Tooling.dll" restore "C:\Users\myusername\Documents\GitHub\cli-samples\HelloMvc" -f "C:\Program Files (x86)\Microsoft Web Tools\DNU"
Microsoft .NET Development Utility Clr-x86-1.0.0-rc2-20221
  CACHE https://www.nuget.org/api/v2/
  CACHE https://www.myget.org/F/aspnetrelease/api/v3/index.json
  CACHE https://api.nuget.org/v3/index.json
Restoring packages for C:\Users\myusername\Documents\GitHub\cli-samples\HelloMvc\project.json
----------
C:\Users\myusername\Documents\GitHub\cli-samples\HelloMvc\project.json(0,0): Error: Microsoft.Dnx.Runtime.FileFormatException: unknown keyword platform ---> System.InvalidOperationException: unknown keyword platform
   at Microsoft.Dnx.Runtime.LibraryDependencyType.Parse(String keyword)
   at Microsoft.Dnx.Runtime.ProjectReader.PopulateDependencies(String projectPath, IList`1 results, JsonObject settings, String propertyName, Boolean isGacOrFrameworkReference)
   at Microsoft.Dnx.Runtime.ProjectReader.ReadProject(Stream stream, String projectName, String projectPath, ICollection`1 diagnostics)
   at Microsoft.Dnx.Runtime.Project.TryGetProject(String path, Project& project, ICollection`1 diagnostics)
   --- End of inner exception stack trace ---
   at Microsoft.Dnx.Runtime.Project.TryGetProject(String path, Project& project, ICollection`1 diagnostics)
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
unknown keyword platform
NuGet Config files used:
    C:\Users\myusername\AppData\Roaming\NuGet\nuget.config
    C:\Users\myusername\Documents\GitHub\cli-samples\nuget.config
Feeds used:
    https://www.nuget.org/api/v2/
    https://www.myget.org/F/aspnetrelease/api/v3/flatcontainer/
    https://api.nuget.org/v3-flatcontainer/
    C:\Program Files (x86)\Microsoft Web Tools\DNU

```

**Comment by moozzyk** [comment]
You are not running dotnet restore. You are running dnx hence the problem. This is what you run to restore as per your post:

C:\Users\myusername\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-20221\bin\dnx.exe "C:\Users\myusername\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-20221\bin\lib\Microsoft.Dnx.Tooling\Microsoft.Dnx.Tooling.dll" restore "C:\Users\myusername\Documents\GitHub\cli-samples\HelloMvc" -f "C:\Program Files (x86)\Microsoft Web Tools\DNU"

**Comment by shima20** [comment]
I've been typing "dotnet restore" in the cmd line though. Why is it running dnx?

**Comment by shima20** [comment]
@moozzyk - For me it seems the problem is this line in the dependencies when I get the "unknown keyword platform" error and the packages restore failes :

```
"Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-*"
    }
```

**Comment by moozzyk** [comment]
You probably have multiple versions of dotnet and one of them is really ancient. AFAIR at the very beginning before the restore logic was moved to dotnet/nuget `dotnet restore` invoked what `dnu restore` did which basically used `dnx`. You need to find it and remove it and possibly remove its folder from the path. dotnet now installs in `Program Files\dotnet`. Instead of running just `dotnet` try using the full path (e.g. `c:\program files\dotnet\dotnet.exe` and see if it helps). 
Changing project.json does not make sense since this is not the problem you have. First removing `"type": "platform"` will change the application from being portable to being standalone and would require adding `"runtimes"` section. Second many names in project.json were changed recently (https://github.com/aspnet/Announcements/issues/175) so I am not positive you would not hit other issues.
