### ISSUE TITLE
Discussion: Removed RuntimeEnvironment

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/PlatformAbstractions#46]
See Announcement: https://github.com/aspnet/Announcements/issues/191

**Comment by Kizmar** [comment]
So what's the new equivalent to the following:
`PlatformServices.Default.Runtime.OperatingSystemPlatform == Platform.Darwin`

**Comment by BrennanConroy** [comment]
System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(OSPlatform.OSX)

**Comment by sunsided** [comment]
I used to check for mono using
```
RuntimeEnvironment _environment = ...

if (string.Equals(_environment.RuntimeType, "Mono", StringComparison.OrdinalIgnoreCase)) {}
```
how is this done now? (I'm _not_ using .NET Core.)

**Comment by BrennanConroy** [comment]
Not sure what the recommended way is right now. You could still do what you used to do but reference the Microsoft.Extensions.RuntimeEnvironment.Sources package (which is not on NuGet). Or you could do what is does internally `#if NET451 Type.GetType("Mono.Runtime") != null ? "Mono" : "CLR" #else ...`

**Comment by hishamco** [comment]
@BrennanConroy I think this should be remove, while `RuntimeEnvironment` is already removed
