### ISSUE TITLE
What is the replacement API?

### ISSUE THREAD

**Issue by smarts** [aspnet/PlatformAbstractions#61]
This repository has been marked as obsolete.

Please open issues on https://github.com/dotnet/corefx if you are having trouble with the replacement API suggested in the README.

^^I don't see any "replacement API suggested in the README". What is the replacement API?

**Comment by BrennanConroy** [comment]
@Eilon 
Here's the old readme https://github.com/aspnet/PlatformAbstractions/blame/80f4e1112c912b331df89bf56bf1587de89be813/README.md

**Comment by Eilon** [comment]
I added back the text to https://github.com/aspnet/PlatformAbstractions.

@smarts thanks for pointing this out!
